[package]
name = "openiap"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
tonic={ version = "0.12.0", features = ["transport", "gzip"] }
prost="0.13.1"
prost-types="0.13.1"
tokio={ version="1.38.0", features =  ["rt", "rt-multi-thread", "macros"] }
tokio-stream = "0.1.15"
tracing = { version="0.1", features = ["log", "attributes" ] }
tracing-subscriber = { version = "0.3.18", features = ["std", "env-filter","json"] }
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
tonic-build = "0.12.0"

