[build]
# default-target = "x86_64-unknown-linux-gnu"

pre-build = [
    "apt-get update && apt-get install --assume-yes protobuf-compiler",
]

# cross build --target x86_64-unknown-linux-gnu
# cross build --target aarch64-unknown-linux-gnu

# cross build --target x86_64-pc-windows-gnu
# cross build --target i686-pc-windows-gnu

# cross build --target aarch64-apple-darwin
# cross build --target x86_64-apple-darwin




# cargo install cross --git https://github.com/cross-rs/cross
# https://github.com/cross-rs/cross-toolchains

[target.x86_64-apple-darwin]
image = "ghcr.io/cross-rs/x86_64-apple-darwin-cross:local"

# apple silicon
[target.aarch64-apple-darwin]
image = "ghcr.io/cross-rs/aarch64-apple-darwin-cross:local"

[target.i686-apple-darwin]
image = "ghcr.io/cross-rs/i686-apple-darwin-cross:local"
build-std = ["std"]
