[build]
default-target = "x86_64-unknown-linux-gnu"

[target.x86_64-apple-darwin]
image = "registry.demo.openiap.io/x86_64-apple-darwin"

[target.aarch64-apple-darwin]
image = "registry.demo.openiap.io/aarch64-apple-darwin"
