[build]
default-target = "x86_64-unknown-linux-gnu"
pre-build = [
    "apt-get update && apt-get install --assume-yes protobuf-compiler curl libc6-dev"
]

[target.aarch64-apple-darwin]
image = "registry.demo.openiap.io/aarch64-apple-darwin"

[target.x86_64-apple-darwin]
image = "registry.demo.openiap.io/x86_64-apple-darwin"

#cross-util run -i -v  --target target.aarch64-apple-darwin -- bash
#cross-util run -i -v  --target target.x86_64-apple-darwin -- bash