[toolchain]
channel = "1.82.0"
components = ["rust-src"]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-gnu",
    "x86_64-pc-windows-msvc",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "aarch64-unknown-linux-gnu"
]
profile = "minimal"

#rustup toolchain install 1.82.0
#rustup override set 1.82.0
