[target.x86_64-unknown-linux-gnu]
runner = "sudo -E"
rustflags = [
    "-C", "link-arg=-lgcc_s",
    "-C", "link-arg=-Wl,--no-as-needed",
    "-C", "link-arg=-ldl"
]

[env]
OPENSSL_NO_PKG_CONFIG = "1"
OPENSSL_STATIC = "1"

[target.x86_64-unknown-linux-musl]
# allow building .so files on musl
rustflags = ["-Ctarget-feature=-crt-static"]

[target.aarch64-unknown-linux-musl]
# allow building .so files on musl
rustflags = ["-Ctarget-feature=-crt-static"]

